language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: na70ASOIlilCMVAe0kT298j65fLiC1D4ksg4DF3Xj+mN0atm89qMVFiPxFZFHSxI3D1MOYr1HkbLqM2Ox4LFC03apuG9AI/OC6fTZgg44y9KOmrWo7oUaH7LiOMk+8qAbGOLr5N0U+G2yTZX+xE27i9r7y3Qp6QH3o7ADZzHWX4LG4KlUBU+ramJCd9W4DHduEpRjB26qzgNSB9DRDW0NMgk1/bPQhHtuB/Vg1Z3aOW8j4XvlSnF3d3s1IJXhxvAp2m3uGsDHL75LMt7mBYM4feCDL7mSu7uApTgn/kT58ANDnXuTCxjp8sK6BBaKdCqSWoH5BDCPOhpX2EgkK/LpRft0xGWkbU8Hk+4zVj6GOkDM6d9agnWO2+4DrhSH/jWPxW/3xfuMlzF2h0S884XKkeHScDqgFdb3xJkiGh2qsexih1P/vT5lIbcW5mhkUneYyZ21Z0as44XFdntdDxG6rQ76cuQdApCNxIuh9Xv95MPBzTN6I95X2wVglrEaEJ4pULwmuOJCqw6TrAkGqk0tBjxJ+L7O0xGlYdpLOIhWBR8huQIURuu5CUVDl8pSZq3oVJRH2T+JauMdbeVMlOdspl/eLSR/y0BIhRMaiNYmEeXtQ5PojgbO+SkENKhEUHwThepM41FQRLD/yjdVW3jZww2GMDbQHcE0YiFcHx25R8=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
